default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: postgres
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Professional123

test:
  <<: *default
  database: tinderbot_test

production:
  <<: *default
  database: postgres
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Professional123